In [2]:
import torch
from torch.utils.data import Dataset


print(globals())

class A(Dataset):
    def __init__(self):
        super().__init__()

        self.data = 1

    def __getitem__(self, index):
        return super().__getitem__(index)
    
    def __len__(self):
        return 0
    
def get_label(dataset):
    print(dataset)
    dataset.data = 999

a = A()

get_label(a)

print(a, a.data)

{'__name__': '__main__', '__doc__': 'Automatically created module for IPython interactive environment', '__package__': None, '__loader__': None, '__spec__': None, '__builtin__': <module 'builtins' (built-in)>, '__builtins__': <module 'builtins' (built-in)>, '_ih': ['', 'import torch\nfrom torch.utils.data import Dataset\n\n\nglobals()\n\nclass A(Dataset):\n    def __init__(self):\n        super().__init__()\n\n        self.data = 1\n\n    def __getitem__(self, index):\n        return super().__getitem__(index)\n    \n    def __len__(self):\n        return 0\n    \ndef get_label(dataset):\n    print(dataset)\n    dataset.data = 999\n\na = A()\n\nget_label(a)\n\nprint(a, a.data)', 'import torch\nfrom torch.utils.data import Dataset\n\n\nprint(globals())\n\nclass A(Dataset):\n    def __init__(self):\n        super().__init__()\n\n        self.data = 1\n\n    def __getitem__(self, index):\n        return super().__getitem__(index)\n    \n    def __len__(self):\n        return 0\n    \ndef 

In [12]:
from pathlib import Path
import json


a = Path("./Dataset") / "metadata.json"

<class 'pathlib.PosixPath'>


In [40]:
sample1 = ([[1,2,3],[4,5,6]], 0)
sample2 = ([[2,3,4],[5,6,7]], 1)
sample3 = ([[9,9,9],[0,0,0]], 2)

samples = [sample1, sample2, sample3]
print(samples, "\n")

# break the list structure
f, l = zip(*samples)
print(f, l)
print(type(f))

# zip object is returned
zipped = zip(sample1, sample2, sample3)
print(type(zipped))
j, k = list(zipped)
print(j, k, "\n")

# automatically zip [1,2] and [] together!
q = list(zip([1,2]))
print(q)

[([[1, 2, 3], [4, 5, 6]], 0), ([[2, 3, 4], [5, 6, 7]], 1), ([[9, 9, 9], [0, 0, 0]], 2)] 

([[1, 2, 3], [4, 5, 6]], [[2, 3, 4], [5, 6, 7]], [[9, 9, 9], [0, 0, 0]]) (0, 1, 2)
<class 'tuple'>
<class 'zip'>
([[1, 2, 3], [4, 5, 6]], [[2, 3, 4], [5, 6, 7]], [[9, 9, 9], [0, 0, 0]]) (0, 1, 2) 

[(1,), (2,)]


In [70]:
import torch
import torch.nn as nn

# a = torch.randint(0, 10, (3, 2, 4))
a = torch.rand(3, 2, 4)
print(a.shape, "\n", a, "\n")

b = a.permute(1, 0, 2)
print(b.shape, "\n", b, "\n")

c = b.transpose(0, 1)
print(c.shape, "\n", c, "\n")

d = c.mean(dim=-1)
print(d)

'''
encoder = nn.TransformerEncoderLayer(d_model=4, nhead=1, batch_first=True)
d = encoder(a)
print(d.shape, "\n", d, "\n")
'''



torch.Size([3, 2, 4]) 
 tensor([[[0.5887, 0.1941, 0.0943, 0.0441],
         [0.6562, 0.9275, 0.0228, 0.9611]],

        [[0.4304, 0.4051, 0.1363, 0.6854],
         [0.3851, 0.9096, 0.8259, 0.0922]],

        [[0.2056, 0.3901, 0.5803, 0.8920],
         [0.0194, 0.0200, 0.2423, 0.6044]]]) 

torch.Size([2, 3, 4]) 
 tensor([[[0.5887, 0.1941, 0.0943, 0.0441],
         [0.4304, 0.4051, 0.1363, 0.6854],
         [0.2056, 0.3901, 0.5803, 0.8920]],

        [[0.6562, 0.9275, 0.0228, 0.9611],
         [0.3851, 0.9096, 0.8259, 0.0922],
         [0.0194, 0.0200, 0.2423, 0.6044]]]) 

torch.Size([3, 2, 4]) 
 tensor([[[0.5887, 0.1941, 0.0943, 0.0441],
         [0.6562, 0.9275, 0.0228, 0.9611]],

        [[0.4304, 0.4051, 0.1363, 0.6854],
         [0.3851, 0.9096, 0.8259, 0.0922]],

        [[0.2056, 0.3901, 0.5803, 0.8920],
         [0.0194, 0.0200, 0.2423, 0.6044]]]) 

tensor([[0.2303, 0.6419],
        [0.4143, 0.5532],
        [0.5170, 0.2215]])


'\nencoder = nn.TransformerEncoderLayer(d_model=4, nhead=1, batch_first=True)\nd = encoder(a)\nprint(d.shape, "\n", d, "\n")\n'

## Type Specific Function?

In [2]:
def type_specific_fn(x : int, y : int, tf: bool=True):
    if tf:
        return x+y
    else:
        return x*y
    
type_specific_fn(3.3, 1, 1)

4.3