In [22]:
import numpy as np

a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)

b = np.array([[[],[],[],[]],[[],[],[],[]]])
print(b.shape)
print(b)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 4, 0)
[]


In [19]:
a = np.zeros((2,3))
print(a)

b = np.full((2, 2), 3.1)
print(b)

c = np.eye(2)
print(c)

d = np.random.random((2,2))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]
[[3.1 3.1]
 [3.1 3.1]]
[[1. 0.]
 [0. 1.]]
[[0.17947836 0.9488231 ]
 [0.73939777 0.44069042]]


In [31]:
h = 'hello'
world = 'world'
print('{} {}'.format(h,world))

hello world


In [ ]:
a = np.array([[1,2,3], [4,5,6]])
r1 = a[1, :]
r2 = a[]

In [8]:
import torch

a = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
a = a.detach()
print(a.requires_grad)

False


In [3]:
class myclass:
    def __init__(self, aclass):
        self.data = aclass.data

class test:
    def __init__(self, data):
        self.data = data

a = [1, 2, 3]
t = test(a)
mc = myclass(t)

print(f"a={a}, test={t.data}, myclass={mc.data}")

a = a + [1, 1, 1]

print(f"a={a}, test={t.data}, myclass={mc.data}")

t.data = [4, 5, 6]

print(f"a={a}, test={t.data}, myclass={mc.data}")

a=[1, 2, 3], test=[1, 2, 3], myclass=[1, 2, 3]
a=[1, 2, 3, 1, 1, 1], test=[1, 2, 3], myclass=[1, 2, 3]
a=[1, 2, 3, 1, 1, 1], test=[4, 5, 6], myclass=[1, 2, 3]


In [8]:
import numpy as np

A = np.array([[1,2,3], [4,5,6],[7,8,9]])

a = A[:2]
print(A)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]


In [ ]:
%pip install 