In [5]:
import torch
import torch.nn as nn


def init_weight(m):
    print(m)
    if type(m) == nn.Linear:
        m.weight.fill_(1.)
        print(m.weight)

class Net(nn.Module):
    def __init__(self):
        super().__init__()

        self.net = nn.Sequential(
            nn.Linear(2, 2),
            nn.ReLU(),
            nn.Linear(2, 3)
        )

with torch.no_grad():
    net = Net()
    net.apply(init_weight)

Linear(in_features=2, out_features=2, bias=True)
Parameter containing:
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
ReLU()
Linear(in_features=2, out_features=3, bias=True)
Parameter containing:
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): ReLU()
  (2): Linear(in_features=2, out_features=3, bias=True)
)
Net(
  (net): Sequential(
    (0): Linear(in_features=2, out_features=2, bias=True)
    (1): ReLU()
    (2): Linear(in_features=2, out_features=3, bias=True)
  )
)


In [8]:
import glob
import os

fnames = glob.glob(os.path.join("./data/faces", "*"))
fnames

['./data/faces/9733.jpg',
 './data/faces/14147.jpg',
 './data/faces/52112.jpg',
 './data/faces/63.jpg',
 './data/faces/6400.jpg',
 './data/faces/34297.jpg',
 './data/faces/42301.jpg',
 './data/faces/24084.jpg',
 './data/faces/13628.jpg',
 './data/faces/65966.jpg',
 './data/faces/23933.jpg',
 './data/faces/12536.jpg',
 './data/faces/54563.jpg',
 './data/faces/823.jpg',
 './data/faces/15259.jpg',
 './data/faces/35189.jpg',
 './data/faces/44770.jpg',
 './data/faces/19463.jpg',
 './data/faces/4217.jpg',
 './data/faces/47279.jpg',
 './data/faces/36480.jpg',
 './data/faces/28866.jpg',
 './data/faces/16750.jpg',
 './data/faces/50705.jpg',
 './data/faces/26693.jpg',
 './data/faces/37946.jpg',
 './data/faces/3578.jpg',
 './data/faces/40516.jpg',
 './data/faces/58359.jpg',
 './data/faces/10321.jpg',
 './data/faces/56374.jpg',
 './data/faces/16988.jpg',
 './data/faces/59047.jpg',
 './data/faces/2666.jpg',
 './data/faces/41608.jpg',
 './data/faces/46167.jpg',
 './data/faces/5109.jpg',
 './data/fac

In [2]:
import torch
from torch.autograd import Variable


a = Variable(torch.randn(2, 3))
a

tensor([[-1.0334,  0.0928, -0.1136],
        [ 0.6429, -1.1292, -1.2708]])

In [16]:
import torch



a = torch.ones((2, 3))
a.to('mps')
a = a.to('mps')
print(a.device)

mps:0
